"""RO-Crate 1.2 export for baselines + optional provenance.

RO-Crate (https://www.researchobject.org/ro-crate/) is a W3C community
standard for packaging research outputs as a JSON-LD metadata file
alongside data files. Makes a MissionCritical-protected paper portable
to any reviewer who understands the standard.

We emit:
  - ro-crate-metadata.json  (top-level manifest)
  - baseline.json            (the numerical corpus, copied)
  - provenance.json          (if present, copied)
  - report.json per paper    (if report file exists, copied)
"""
from __future__ import annotations

import shutil
from pathlib import Path

from mission_critical.baseline.store import BaselineStore

try:
    from rocrate.rocrate import ROCrate  # type: ignore[import-untyped]
    _HAS_ROCRATE = True
except ImportError:
    _HAS_ROCRATE = False


def build_crate(
    baseline_path: Path,
    out_dir: Path,
    *,
    provenance_path: Path | None = None,
    report_paths: list[Path] | None = None,
    name: str | None = None,
    description: str | None = None,
) -> Path:
    """Write an RO-Crate 1.2 at `out_dir` containing baseline + optional
    provenance + any report files supplied.

    Returns the out_dir path. Raises RuntimeError if rocrate-py isn't
    installed.
    """
    if not _HAS_ROCRATE:
        raise RuntimeError(
            "rocrate-py not installed. pip install rocrate."
        )

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Read baseline to extract paper summary for the crate's description
    store = BaselineStore(baseline_path)
    records = store.all()
    papers = [r.paper_id for r in records]
    if name is None:
        name = f"MissionCritical baseline crate ({len(papers)} paper(s))"
    if description is None:
        description = (
            "Numerical baseline corpus for meta-analysis papers "
            f"({', '.join(papers)}). Generated by MissionCritical."
        )

    crate = ROCrate()
    crate.name = name
    crate.description = description

    # Copy + register baseline.json
    baseline_dest = out_dir / "baseline.json"
    shutil.copy(baseline_path, baseline_dest)
    crate.add_file(
        baseline_dest,
        properties={
            "@type": "File",
            "encodingFormat": "application/json",
            "description": "MissionCritical numerical-baseline corpus",
        },
    )

    if provenance_path is not None and Path(provenance_path).is_file():
        prov_dest = out_dir / "provenance.json"
        shutil.copy(provenance_path, prov_dest)
        crate.add_file(
            prov_dest,
            properties={
                "@type": "File",
                "encodingFormat": "application/json",
                "description": "MissionCritical provenance store",
            },
        )

    for rp in (report_paths or []):
        rp = Path(rp)
        if not rp.is_file():
            continue
        dest = out_dir / rp.name
        shutil.copy(rp, dest)
        crate.add_file(
            dest,
            properties={
                "@type": "File",
                "encodingFormat": "application/json",
                "description": f"Paper re-run report: {rp.stem}",
            },
        )

    # Write the crate metadata to out_dir/ro-crate-metadata.json
    crate.write(out_dir)
    return out_dir
